In [1]:
import numpy as no

In [2]:
import numpy as np      # ipynb - interactive python notebook
# it is writtten in c language and it is used as python. 
#  Since python has no array we use numpy library
# it is used for storing multidimensional data and can perform many operations and process data

# to add 5 marks for every marks
marks=np.array([80,90,78,88,98])
marks+5
marks/2
marks+5 # here we are just calculating and not printing

array([ 85,  95,  83,  93, 103])

In [3]:
marks=marks-5  # here we store the value and printing
marks/2
print(marks)

[75 85 73 83 93]


In [4]:
print(marks[3])
print(marks[2])
print(marks[1])

83
73
85


In [5]:
%pip install numpy


import numpy as np

marks = np.array([88, 75, 66, 99])

print("Original Marks:", marks)
print("Marks + 5:", marks + 5)
print("Marks - 5:", marks - 5)
print("Marks / 2:", marks / 2)

marks = np.array([88, 75, 66, 99])

print("Original Marks:", marks)
print("Marks + 5:", marks + 5)
print("Marks - 5:", marks - 5)
print("Marks / 2:", marks / 2)

Original Marks: [88 75 66 99]
Marks + 5: [ 93  80  71 104]
Marks - 5: [83 70 61 94]
Marks / 2: [44.  37.5 33.  49.5]
Original Marks: [88 75 66 99]
Marks + 5: [ 93  80  71 104]
Marks - 5: [83 70 61 94]
Marks / 2: [44.  37.5 33.  49.5]


In [6]:
print (marks)

[88 75 66 99]


In [8]:
print(marks[-2])
print(marks[-3])
print(marks[-1])
print(marks[-4])

66
75
99
88


In [9]:
print(marks[-2])
print(marks[-3])
print(marks[-1])
print(marks[-4])

66
75
99
88


In [10]:
for i in range(4):
    print(marks[i])

88
75
66
99


In [11]:
marks[:2] # Academic team wants first 2 marks
marks[1:4]

array([75, 66, 99])

In [28]:
import numpy as np

marks = np.array([
    [85, 78, 90],
    [92, 85, 98],
    [76, 82, 80]
])

    #Rows -> Students
    #Columns -> Subjects

In [15]:
marks[0,0]

np.int32(85)

In [16]:
marks[0:1][0:2]

array([[85, 78, 90]])

In [18]:
marks[0:2]
marks[0:2,0:2]

array([[85, 78],
       [92, 85]])

In [19]:
marks[0][0]
marks[0:2][0:2]

array([[85, 78, 90],
       [92, 85, 98]])

In [20]:
print(marks[1:,0])
print(marks[0:][0])

[92 76]
[85 78 90]


In [21]:
print(marks[1:,0])
print(marks[1:][0])

[92 76]
[92 85 98]


In [22]:
print(marks[1:,0])

[92 76]


In [23]:
print(marks[1:][0])

[92 85 98]


print(marks[0][0:2])

In [44]:
#combining batch1 & batch2
b1=np.array([56,78,89])
b2=np.array([65,76,98])
comb=np.concatenate((b1, b2))
comb
# it display in scalar form

array([56, 78, 89, 65, 76, 98])

In [36]:
print(np.split(comb,2))

[array([[56],
       [78],
       [89]]), array([[65],
       [76],
       [98]])]


In [40]:
#A combined dataset contains six students. The academic team wants to divide the data into two groups for separate processing.
print(np.split(comb,2))

for arr in np.split(comb,3):
    print(arr)

[array([[56],
       [78],
       [89]]), array([[65],
       [76],
       [98]])]
[[56]
 [78]]
[[89]
 [65]]
[[76]
 [98]]


In [48]:
b1=np.array([[56,78,89],[34,45,67]])
b2=np.array([[85,78,90],[89,98,78]])

comb1=np.concatenate((b1, b2),axis=1)
#array[[56 78 89 85 78 90]
# [34 45 67 89 98 78]]
print(comb1)
print("-------------")
comb0=np.concatenate((b1,b2),axis=1)
comb0

[[56 78 89 85 78 90]
 [34 45 67 89 98 78]]
-------------


array([[56, 78, 89, 85, 78, 90],
       [34, 45, 67, 89, 98, 78]])

In [49]:
#find where the mark is 78
np.where(marks==78)

(array([0]), array([1]))

In [51]:
#find marks greater then 70
np.where(marks>70)
print(marks)

[[85 78 90]
 [92 85 98]
 [76 82 80]]


In [52]:
#find marks greater then 70
marks=np.array([[85,78,90],
[92,85,99],
[75,82,80]])
print(np.where(marks>70))
print(marks)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))
[[85 78 90]
 [92 85 99]
 [75 82 80]]


In [54]:
#find marks greater then 80
marks=np.array([[85,78,90],
[92,85,99],
[75,82,80]])
print(np.where(marks>=80))
print(marks)

(array([0, 0, 1, 1, 1, 2, 2]), array([0, 2, 0, 1, 2, 1, 2]))
[[85 78 90]
 [92 85 99]
 [75 82 80]]


In [56]:
#find marks greater then 80
marks=np.array([[85,78,90],
[92,85,99],
[75,82,80]])
np.where(marks>=80) #--> gives me indicates
print(marks[np.where(marks>=80)]) # ---> gives exact values
print(marks)

[85 90 92 85 99 82 80]
[[85 78 90]
 [92 85 99]
 [75 82 80]]


In [58]:
#sort this array
np.sort(marks)
np.sort(marks)[::-1] # reverse array

array([[75, 80, 82],
       [85, 92, 99],
       [78, 85, 90]])

In [60]:
np.sort(marks,axis=1) #y-axis

array([[78, 85, 90],
       [85, 92, 99],
       [75, 80, 82]])

In [61]:
np.sort(marks,axis=0) #x-axis

array([[75, 78, 80],
       [85, 82, 90],
       [92, 85, 99]])